apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ng.fullname" . }}
  labels:
    {{- include "paperless-ng.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "paperless-ng.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "paperless-ng.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "paperless-ng.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "redis:6.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: redis
          readinessProbe:
            tcpSocket:
              port: redis
        - name: {{ .Chart.Name }}
          env:
          {{- if .Values.paperless.config.dbhost }}
          - name: PAPERLESS_DBHOST
            value: {{ .Values.paperless.config.dbhost | quote }}
          {{- end }}
          {{- if .Values.paperless.config.dbport }}
          - name: PAPERLESS_DBPORT
            value: {{ .Values.paperless.config.dbport | quote }}
          {{- end }}
          {{- if .Values.paperless.config.dbuser }}
          - name: PAPERLESS_DBUSER
            value: {{ .Values.paperless.config.dbuser | quote }}
          {{- end }}
          {{- if .Values.paperless.config.dbpass }}
          - name: PAPERLESS_DBPASS
            value: {{ .Values.paperless.config.dbpass | quote }}
          {{- end }}
          {{- if .Values.paperless.config.dbsslmode }}
          - name: PAPERLESS_DBSSLMODE
            value: {{ .Values.paperless.config.dbsslmode | quote }}
          {{- end }}
          {{- if .Values.paperless.config.consumption_dir }}
          - name: PAPERLESS_CONSUMPTION_DIR
            value: {{ .Values.paperless.config.consumption_dir | quote }}
          {{- end }}
          {{- if .Values.paperless.config.data_dir }}
          - name: PAPERLESS_DATA_DIR
            value: {{ .Values.paperless.config.data_dir | quote }}
          {{- end }}
          {{- if .Values.paperless.config.media_root }}
          - name: PAPERLESS_MEDIA_ROOT
            value: {{ .Values.paperless.config.media_root | quote }}
          {{- end }}
          {{- if .Values.paperless.config.static_dir }}
          - name: PAPERLESS_STATICDIR
            value: {{ .Values.paperless.config.static_dir | quote }}
          {{- end }}
          {{- if .Values.paperless.config.consumer_polling }}
          - name: PAPERLESS_CONSUMER_POLLING
            value: {{ .Values.paperless.config.consumer_polling | quote }}
          {{- end }}
          {{- if .Values.paperless.config.admin_user }}
          - name: PAPERLESS_ADMIN_USER
            value: {{ .Values.paperless.config.admin_user | quote }}
          {{- end }}
          {{- if .Values.paperless.config.admin_password }}
          - name: PAPERLESS_ADMIN_PASSWORD
            value: {{ .Values.paperless.config.admin_password | quote }}
          {{- end }}
          {{- if .Values.paperless.config.auto_login_username }}
          - name: PAPERLESS_AUTO_LOGIN_USERNAME
            value: {{ .Values.paperless.config.auto_login_username | quote }}
          {{- end }}
          {{- if .Values.paperless.config.enable_http_remote_user }}
          - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
            value: {{ .Values.paperless.config.enable_http_remote_user | quote }}
          {{- end }}
          {{- if .Values.paperless.config.http_remote_user_header_name }}
          - name: PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME
            value: {{ .Values.paperless.config.http_remote_user_header_name | quote }}
          {{- end }}
          {{- if .Values.paperless.config.url }}
          - name: PAPERLESS_URL
            value: {{ .Values.paperless.config.url | quote }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- if .Values.persistentVolumeClaim.enabled }}
          volumeMounts:
          - mountPath: {{ .Values.persistentVolumeClaim.mountPath }}
            name: {{ .Chart.Name }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistentVolumeClaim.enabled }}
      volumes:
      - name: {{ .Chart.Name }}
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
