{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hive-prometheus-exporter.fullname" . }}
  labels:
    {{- include "hive-prometheus-exporter.labels" . | nindent 4 }}
spec:
  jobLabel: {{ .Values.serviceMonitor.jobLabel | quote }}
  selector:
    matchLabels:
      {{- include "hive-prometheus-exporter.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: http
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings: {{ toYaml .Values.serviceMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings: {{ toYaml .Values.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
{{- end -}}
